storage:
  root: ./data/storage
spring:
  datasource:
    url: jdbc:h2:mem:immotool;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update        # erstellt/aktualisiert Tabellen automatisch
    properties:
      hibernate.format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  vaadin:
    launch-browser: true
server:
  port: 8080
